language: ruby
rvm:
  - 1.9.2
  - 1.9.3
notifications:
  email:
    - shift@someone.section.me
env:
  - PUPPET_VERSION=2.7.17
  - PUPPET_VERSION=2.7.18
  - PUPPET_VERSION=3.0.1
  - PUPPET_VERSION=3.1.0
